# Generated by Django 3.1.1 on 2021-06-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractdepartment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractdepartment',
            name='parent_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.abstractdepartment'),
        ),
        migrations.AlterField(
            model_name='abstractdepartment',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
