# Generated by Django 3.1.1 on 2021-06-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_feature_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department'),
        ),
    ]
