# Generated by Django 3.1.1 on 2021-06-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210604_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractdepartment',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.abstractdepartment'),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='abstractfeature',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
