# Generated by Django 3.1.1 on 2021-06-05 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210605_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='store.department'),
        ),
    ]
