# Generated by Django 3.1.1 on 2021-06-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210605_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, db_column='parent_department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_department_id', to='store.department'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='department',
            field=models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='store.department'),
        ),
    ]
