# Generated by Django 3.1.1 on 2021-06-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210605_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, db_column='parent_department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_id', to='store.department'),
        ),
    ]
