# Generated by Django 3.1.1 on 2021-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210605_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
